#!/bin/sh

# ENV
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_QPA_PLATFORMTHEME="qt6ct"
export EDITOR="nvim"
export BROWSER="firefox"
export TERMINAL="kitty"

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

  xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

  xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Display
xrandr --output DP-0 --mode 3440x1440 --rate 165 --dpi 96 &
nitrogen --set-auto --random &
picom -b &

# Applications
dunst &
blueman-applet &
steam -silent &
discord --start-minimized &
nm-applet &
pasystray &
dwmblocks &
sunshine &

# Services
/usr/lib/polkit-kde-authentication-agent-1 &
unclutter -idle 1 &
#easyeffects --gapplication-service &

# Set key repeat rate (Set globally in /etc/X11/xinit/xinitrc.d/ for now)
xset r rate 250 50 &

# Key remaps
setxkbmap -option caps:escape &

# Start dwm
exec dwm
