#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# DWM
setxkbmap -option caps:escape &
source .zprofile &
nitrogen --restore &
picom -b --experimental-backends &
dwmblocks &
dunst &
nm-applet &
steam --silent &
pcmanfm -d &
pasystray &
discord --start-minimized &
blueman-applet &
/opt/piavpn/bin/pia-client &
[ ! -s ~/.config/mpd/pid ] && mpd &
easyeffects --gapplication-service &
exec dwm
