wallpaper {
    monitor = DP-2
    path = ~/Pictures/Wallpapers/3440x1440/
    recursive = true
    order = random
    fit_mode = contain
    timeout = 300
  }

wallpaper {
    monitor = HEADLESS-2
    path = ~/Pictures/Wallpapers/iPad/
    recursive = true
    order = random
    fit_mode = contain
    timeout = 30
  }

  splash = false
