## Rose Pine
import = [
  # "~/.config/alacritty/Themes/Rose_Pine/rose-pine.toml",
  # "~/.config/alacritty/Themes/Tokyo_Night/tokyo-night.toml",
  "~/.config/alacritty/Themes/Tokyo_Night/tokyo-night-storm.toml",
  # "~/.config/alacritty/Themes/Dracula/dracula.toml",
]
live_config_reload = true



# General Settings
[env]
TERM = "alacritty"

[mouse]
hide_when_typing = true

[window]
opacity = 0.5

[window.dimensions]
columns = 150
lines = 35

[window.padding]
x = 20
y = 20


# Font
[font.normal]
#family = "SauceCodePro Nerd Font"
family = "JetBrainsMono Nerd Font"
#family = "RobotoMono Nerd Font Mono"
#family = "CaskaydiaCove Nerd Font"

# style = "Regular"
style = "Medium"
# style = "Bold"

[font]
size = 14.0
