#!/bin/bash

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

xrandr --dpi 96

picom & 
steam --silent &
sxhkd &
discord --start-minimized &
dunst & 
nm-applet &
pcmanfm -d &
pasystray &
[ ! -s ~/.config/mpd/pid ] && mpd &
easyeffects --gapplication-service &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dwmblocks & 
setxkbmap -option caps:escape,shift:both_capslock &

# Ensure xrdb has finished before moving on to start the WM/DE
[ -n "$xrdbpid" ] && wait "$xrdbpid"
