#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
  . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
    . "$HOME/.xprofile"
fi

ssh-agent dwm



#nitrogen --restore &
#picom -b --experimental-backends &
#dunst &
#nm-applet &
#vmware &
#steam --silent &
#pcmanfm -d &
#pasystray &
#discord --start-minimized &
#/opt/piavpn/bin/pia-client &
#[ ! -s ~/.config/mpd/pid ] && mpd &
#easyeffects --gapplication-service &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#sh /home/jake/Git/dwm-bar/dwm_bar.sh &
#exec dwm
