#  █████╗ ██╗   ██╗████████╗ ██████╗ ███████╗████████╗ █████╗ ██████╗ ████████╗
# ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗╚══██╔══╝
# ███████║██║   ██║   ██║   ██║   ██║███████╗   ██║   ███████║██████╔╝   ██║   
# ██╔══██║██║   ██║   ██║   ██║   ██║╚════██║   ██║   ██╔══██║██╔══██╗   ██║   
# ██║  ██║╚██████╔╝   ██║   ╚██████╔╝███████║   ██║   ██║  ██║██║  ██║   ██║   
# ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   

# Bitwarden Web Fix
exec-once = $HOME/.local/bin/scripts/bitwardenhypr_fix
##

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
##

exec-once = hyprctl output create HEADLESS HEADLESS-2

# Applications
exec-once = mako
exec-once = waybar -c ~/.config/waybar/config.jsonc
exec-once = [workspace 2 silent] firefox
exec-once = [workspace 3 silent] firefoxpwa site launch 01KN2MKV58Q7N04YFXAT3G9BPJ # Claude
exec-once = [workspace 4 silent] env "WINEPREFIX=/home/jake/Wine/foobar2000" wine "C:\\\\ProgramData\\\\Microsoft\\\\Windows\\\\Start Menu\\\\Programs\\\\foobar2000.lnk" # foobar2000
exec-once = [workspace 5 silent] Telegram
exec-once = steam -silent
exec-once = discord
exec-once = easyeffects
exec-once= /opt/piavpn/bin/pia-client --quiet
exec-once = nm-applet
exec-once = xrdb ~/.Xresources
##

