#  █████╗ ██╗   ██╗████████╗ ██████╗ ███████╗████████╗ █████╗ ██████╗ ████████╗
# ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗╚══██╔══╝
# ███████║██║   ██║   ██║   ██║   ██║███████╗   ██║   ███████║██████╔╝   ██║   
# ██╔══██║██║   ██║   ██║   ██║   ██║╚════██║   ██║   ██╔══██║██╔══██╗   ██║   
# ██║  ██║╚██████╔╝   ██║   ╚██████╔╝███████║   ██║   ██║  ██║██║  ██║   ██║   
# ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   


# Wallpaper
# exec-once = awww-daemon
# exec-once = $HOME/.local/bin/scripts/swwwslideshow.sh ~/Pictures/Wallpapers
##

# Bitwarden Web Fix
exec-once = $HOME/.local/bin/scripts/bitwardenhypr_fix
##

# Clipboard
# exec-once = wl-paste --type text --watch cliphist store # Stores only text data
# exec-once = wl-paste --type image --watch cliphist store # Stores only image data
##

## Hypr
# exec-once = systemctl --user start hyprpolkitagent.service 


# Headless Display
# exec-once = hyprctl output create headless HEADLESS-2
##

# Applications
exec-once = sunshine
exec-once = mako
exec-once = waybar -c ~/.config/waybar/config.jsonc
exec-once = [workspace 2 silent] firefox
exec-once = [workspace 5 silent] Telegram
exec-once = steam
exec-once = discord
exec-once= /opt/piavpn/bin/pia-client --quiet
exec-once = nm-applet
exec-once = xrdb ~/.Xresources
##

