# ██████╗ ███████╗ ██████╗██╗  ██╗███████╗██████╗ 
# ██╔══██╗██╔════╝██╔════╝██║ ██╔╝██╔════╝██╔══██╗
# ██║  ██║█████╗  ██║     █████╔╝ █████╗  ██████╔╝
# ██║  ██║██╔══╝  ██║     ██╔═██╗ ██╔══╝  ██╔══██╗
# ██████╔╝███████╗╚██████╗██║  ██╗███████╗██║  ██║
# ╚═════╝ ╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

decoration {
    rounding = 8
    active_opacity = 1.0
    inactive_opacity = 1.0
    blur {
        enabled = true
        size = 8
        passes = 4
        noise = 0.02
        contrast = 1
        brightness = 1
        new_optimizations = true
        xray = true
        vibrancy = 0.1696
        special = true
    }
  shadow {
    range = 4

  }
}
