# ██╗      █████╗ ██╗   ██╗ ██████╗ ██╗   ██╗████████╗
# ██║     ██╔══██╗╚██╗ ██╔╝██╔═══██╗██║   ██║╚══██╔══╝
# ██║     ███████║ ╚████╔╝ ██║   ██║██║   ██║   ██║   
# ██║     ██╔══██║  ╚██╔╝  ██║   ██║██║   ██║   ██║   
# ███████╗██║  ██║   ██║   ╚██████╔╝╚██████╔╝   ██║   
# ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝  ╚═════╝    ╚═╝   

general {
    # layout = scrolling
    layout = master
    gaps_in = 10
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(7aa2f7ff) rgba(bb9af7ff) 45deg # Gradient Tokyo Night
    # col.active_border   = rgba(7aa2f7ff) # Tokyo Night
    col.inactive_border = rgba(414868ff)
    resize_on_border = false
    allow_tearing = true
}

misc {
    enable_swallow = true
    swallow_regex = ^(Alacritty|kitty|foot|ghostty)$
    on_focus_under_fullscreen = true
}

master {
    new_status = master
    allow_small_split = false
    special_scale_factor = 1
    mfact = 0.5
    new_status = master
    new_on_top = false
    new_on_active = none
    orientation = left
    smart_resizing = true
    drop_at_cursor = true
}
# Master-Layout Binds
binde = $META, j, layoutmsg, cyclenext
binde = $META, k, layoutmsg, cycleprev
binde = $META, RETURN, layoutmsg, swapwithmaster master
binde = $META, M, fullscreen

# Scrolling Testing
scrolling {
  fullscreen_on_one_column = true
  column_width = 0.9
  direction = right
}

# bind = $META, period, layoutmsg, move +col
# bind = $META, comma, layoutmsg, move -col
# bind = $META SHIFT, period, layoutmsg, swapcol r
# bind = $META SHIFT, comma, layoutmsg, swapcol l
